name: sharding-repl-cache

services:

  # Приложение
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - redis
      - mongos_router
    restart: always
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"

  # Кэширование
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data

  # Роутер mongos
  mongos_router:
    container_name: mongos_router
    image: dh-mirror.gitverse.ru/mongo:latest
    depends_on:
      - "configSrv"
      - "shard1-a"
      - "shard1-b"
      - "shard1-c"
      - "shard2-a"
      - "shard2-b"
      - "shard2-c"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-router-data:/data/db
    command: [ "mongos", "--configdb", "config_server/configSrv:27019", "--bind_ip_all", ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # Конфигурационный сервер
  configSrv:
    restart: always
    container_name: configSrv
    image: dh-mirror.gitverse.ru/mongo:latest
    volumes:
      - mongodb-config-data:/data/db
    command: [ "--configsvr", "--replSet", "config_server", "--bind_ip_all"] 
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27019" ]
      interval: 5s
      start_period: 10s

  # Шард 1
  shard1-a:
    container_name: shard1-a
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    volumes:
      - mongodb-shard1-a-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard1", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018" ]
      interval: 5s
      start_period: 10s
  shard1-b:
    container_name: shard1-b
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    volumes:
      - mongodb-shard1-b-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard1", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018" ]
      interval: 5s
      start_period: 10s
  shard1-c:
    container_name: shard1-c
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    volumes:
      - mongodb-shard1-c-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard1", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018" ]
      interval: 5s
      start_period: 10s

  # Шард 2
  shard2-a:
    container_name: shard2-a
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    volumes:
      - mongodb-shard2-a-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard2", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018" ]
      interval: 5s
      start_period: 10s
  shard2-b:
    container_name: shard2-b
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    volumes:
      - mongodb-shard2-b-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard2", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018" ]
      interval: 5s
      start_period: 10s
  shard2-c:
    container_name: shard2-c
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    volumes:
      - mongodb-shard2-c-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard2", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018" ]
      interval: 5s
      start_period: 10s

volumes:
  redis-data:
  mongodb-router-data:
  mongodb-config-data:
  mongodb-shard1-a-data:
  mongodb-shard1-b-data:
  mongodb-shard1-c-data:
  mongodb-shard2-a-data:
  mongodb-shard2-b-data:
  mongodb-shard2-c-data:
